server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

  config:
    import: optional:classpath:secrets.properties

groq:
  api:
    key: ${GROQ_API_KEY}